package main

//
// A word-count application "plugin" for MapReduce.
//
// 	>_ go build -buildmode=plugin wc.go
//

import "6.5840/mr"
import "unicode"
import "strings"
import "strconv"

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
// Note: the returned key-value pairs slice may contain multiple values per key.
// When a word occurs multiple times, it gets added to the list again as
// a separate entry. If the word "apple" appears 3 times in your file, your
// output list will contain three separate pairs that look identical:
// 		{"apple", "1"}, {"apple", "1"}, and {"apple", "1"}.
func Map(filename string, contents string) []mr.KeyValue {
	// Function to detect word separators.
	// In Go, 'rune' is a data type that represents a single Unicode character.
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// Split contents into an array of words.
	words := strings.FieldsFunc(contents, ff)

	kva := []mr.KeyValue{}
	for _, w := range words {
		kv := mr.KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// Return the number of occurrences of this word.
	// Note: Since our Map only outputs single key-value pairs with value 1,
	// it is enough to just count them.
	return strconv.Itoa(len(values))
}
